name: benchmark_harness
version: 2.3.1-wip
description: The official Dart project benchmark harness.
repository: https://github.com/dart-lang/benchmark_harness

topics:
 - benchmarking

environment:
  sdk: ^3.2.0

dependencies:
  analyzer: ^6.8.0
  ansicolor: ^2.0.3
  args: ^2.5.0
  build: ^2.4.1
  dcli: ^6.0.5
  ffi: ^2.1.3
  source_gen: ^1.5.0
  stats: ^2.1.0
  # Depend on unreleased version of native_stack_traces.
  native_stack_traces: any
  dart_internal:
    path: ./dart_internal

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.0
  dart_flutter_team_lints: ^3.0.0
  path: ^1.8.0
  test: ^1.16.0
